version: '2'

services:
  portainer:
    image: portainer/portainer
    volumes:
      - "/var/portainer:/data"
      - "/var/run/docker.sock:/var/run/docker.sock"
    restart: always
    ports:
      - "9000:9000"
  plex:
    image: plexinc/pms-docker
    volumes:
      - "/var/plex/config:/config"
      - "/var/plex/transcode:/transcode"
      - "/var/plex/data:/data"
    ports:
      - "32400:32400"
      - "3005:3005"
      - "8324:8324"
      - "32469:32469"
      - "1900:1900"
      - "32410:32410"
      - "32412:32412"
      - "32413:32413"
      - "32414:32414"
    environment:
      TZ: "America/New_York"
      ADVERTISE_IP: "https://plex.local.johnjonesfour.com"
    env_file:
      - /var/serverconfig/env/plex.secret.env
    hostname: plex.local.johnjonesfour.com
    restart: always
  rolodex:
    image: johnjones4/rolodex
    restart: always
    env_file:
      - /var/serverconfig/env/rolodex.secret.env
    environment:
      TZ: "America/New_York"
      DB_PATH: postgres://personalserver:personalserver@postgres/rolodex
      ROOT_URL: https://rolodex.local.johnjonesfour.com
      UPLOAD_DIR: /var/rolodex/uploads
    links:
      - "postgres:postgres"
    volumes:
      - "/var/rolodex:/var/rolodex"
    ports:
      - "8000:8000"
  postgres:
    build: ./postgres
    env_file:
      - ./env/postgres.env
    ports:
      - "5432:5432"
    volumes:
      - "/var/postgres:/var/lib/postgresql/data"
    restart: always
  feedpage:
    image: johnjones4/feedpage
    restart: always
    environment:
      TZ: "America/New_York"
      OPML_URL: https://gist.githubusercontent.com/johnjones4/0fd1b1b47d62d826164bea99015e5fbe/raw/
      PORT: 10000
      NAME: John's Feed
    ports:
      - "10000:10000"
  backup:
    env_file:
      - ./env/postgres.env
    environment:
      - POSTGRES_HOST=postgres
    build: ./backup
    links:
      - "postgres:postgres"
    volumes:
      - "/var/serverbackups:/backups"
      - "/var/portainer:/containers/portainer"
      - "/var/plex:/containers/plex"
      - "/var/serverconfig:/containers/serverconfig"
      - "/var/serverconfig/rclone:/root/.config/rclone"
      - "/var/rolodex:/containers/rolodex"
