version: '2'

services:
  # nginx:
  #   image: nginx
  #   volumes:
  #     - "./nginx:/etc/nginx/conf.d"
  #   ports:
  #     - "80:80"
  #   restart: always
  #   links:
  #     - "portainer:portainer"
  #     - "plex:plex"
  #     - "rolodex:rolodex"
  portainer:
    image: portainer/portainer
    volumes:
      - "portainer:/data"
      - "/var/run/docker.sock:/var/run/docker.sock"
    restart: always
    ports:
      - "9000:9000"
  plex:
    image: plexinc/pms-docker
    volumes:
      - "./plex/config:/config"
      - "./plex/transcode:/transcode"
      - "./plex/data:/data"
    ports:
      - "32400:32400"
      - "3005:3005"
      - "8324:8324"
      - "32469:32469"
      - "1900:1900"
      - "32410:32410"
      - "32412:32412"
      - "32413:32413"
      - "32414:32414"
    environment:
      TZ: "America/New_York"
      ADVERTISE_IP: "http://plex.local.johnjonesfour.com:32400"
    env_file:
      - ./env/plex.secret.env
    hostname: plex.local.johnjonesfour.com
    restart: always
  doomsdaymachine:
    build: ./Doomsday-Machine-2
    restart: always
    environment:
      RETENTION_DAYS: 5
      RCLONE_REMOTES: GoogleDrive:Dropbox
      GITHUB_USER: johnjones4
    volumes:
      - "./doomsday-machine/files/workdir:/var/cloudbackups/workdir"
      - "./doomsday-machine/files/archives:/var/cloudbackups/archives"
      - "./doomsday-machine/config/lastpass:/root/.lpass"
      - "./doomsday-machine/config/geeknote:/root/.geeknote"
      - "./doomsday-machine/config/imap:/root/.imap-backup"
      - "./doomsday-machine/config/rclone:/root/.config/rclone"
      - "./doomsday-machine/config/conf:/etc/cloudbackup"
  rolodex:
    image: johnjones4/rolodex
    restart: always
    env_file:
      - ./env/rolodex.secret.env
    environment:
      DB_PATH: /var/rolodex/db.sqlite
      ROOT_URL: rolodex.local.johnjonesfour.com
      UPLOAD_DIR: /var/rolodex/uploads
    volumes:
      - "./rolodex:/var/rolodex"
    expose:
      - "8000:8000"
  backup:
    build: ./backup
    volumes:
      - "./backups:/backups"
      - "./doomsday-machine/config:/containers/doomsday-machine"
      - "./plex:/containers/plex"
      - "./doomsday-machine/config/rclone:/root/.config/rclone"
      - "./rolodex:/containers/rolodex"
volumes:
  portainer:
