version: '2'

services:
  rolodex:
    image: johnjones4/rolodex
    restart: always
    env_file:
      - /var/serverconfig/env/rolodex.secret.env
    environment:
      TZ: "America/New_York"
      DB_PATH: postgres://personalserver:personalserver@postgres/rolodex
      ROOT_URL: https://rolodex.local.johnjonesfour.com
      UPLOAD_DIR: /var/rolodex/uploads
    links:
      - "postgres:postgres"
    volumes:
      - "/var/rolodex:/var/rolodex"
    ports:
      - "8000:8000"
  postgres:
    build: ./postgres
    env_file:
      - ./env/postgres.env
    ports:
      - "5432:5432"
    volumes:
      - "/var/postgres:/var/lib/postgresql/data"
    restart: always
  feedpage:
    image: johnjones4/feedpage
    restart: always
    environment:
      TZ: "America/New_York"
      OPML_URL: https://gist.githubusercontent.com/johnjones4/0fd1b1b47d62d826164bea99015e5fbe/raw/
      PORT: 10000
      NAME: John's Feed
    ports:
      - "10000:10000"