version: '2'

services:
  portainer:
    image: portainer/portainer
    volumes:
      - "portainer:/data"
      - "/var/run/docker.sock:/var/run/docker.sock"
    restart: always
    ports:
      - "9000:9000"
  plex:
    image: plexinc/pms-docker
    volumes:
      - "./plex/config:/config"
      - "./plex/transcode:/transcode"
      - "./plex/data:/data"
    ports:
      - "32400:32400"
      - "3005:3005"
      - "8324:8324"
      - "32469:32469"
      - "1900:1900"
      - "32410:32410"
      - "32412:32412"
      - "32413:32413"
      - "32414:32414"
    environment:
      TZ: "America/New_York"
      ADVERTISE_IP: "https://plex.local.johnjonesfour.com"
    env_file:
      - ./env/plex.secret.env
    hostname: plex.local.johnjonesfour.com
    restart: always
  doomsdaymachine:
    build: ./Doomsday-Machine-2
    restart: always
    environment:
      RETENTION_DAYS: 5
      RCLONE_REMOTES: GoogleDrive:Dropbox
      GITHUB_USER: johnjones4
      PORT: 12000
    ports:
      - "12000:12000"
    volumes:
      - "./doomsday-machine/files/workdir:/var/cloudbackups/workdir"
      - "./doomsday-machine/files/archives:/var/cloudbackups/archives"
      - "./doomsday-machine/config/lastpass:/root/.lpass"
      - "./doomsday-machine/config/geeknote:/root/.geeknote"
      - "./doomsday-machine/config/imap:/root/.imap-backup"
      - "./doomsday-machine/config/rclone:/root/.config/rclone"
      - "./doomsday-machine/config/conf:/etc/cloudbackup"
  rolodex:
    image: johnjones4/rolodex
    restart: always
    env_file:
      - ./env/rolodex.secret.env
    environment:
      TZ: "America/New_York"
      DB_PATH: postgres://personalserver:personalserver@postgres/rolodex
      ROOT_URL: rolodex.local.johnjonesfour.com
      UPLOAD_DIR: /var/rolodex/uploads
    links:
      - "postgres:postgres"
    volumes:
      - "./rolodex:/var/rolodex"
    ports:
      - "8000:8000"
  postgres:
    build: ./postgres
    env_file:
      - ./env/postgres.env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  feedpage:
    image: johnjones4/feedpage
    restart: always
    environment:
      TZ: "America/New_York"
      OPML_URL: https://gist.githubusercontent.com/johnjones4/0fd1b1b47d62d826164bea99015e5fbe/raw/
      PORT: 10000
    ports:
      - "10000:10000"
  backup:
    env_file:
      - ./env/postgres.env
    environment:
      - POSTGRES_HOST=postgres
    build: ./backup
    links:
      - "postgres:postgres"
    volumes:
      - "./backups:/backups"
      - "./doomsday-machine/config:/containers/doomsday-machine"
      - "./plex:/containers/plex"
      - "./doomsday-machine/config/rclone:/root/.config/rclone"
      - "./rolodex:/containers/rolodex"
volumes:
  portainer:
  pgdata:
